/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setorhafalan;

/**
 *
 * @author xatalie
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingnum = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        logo = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Hafal Quran");
        setUndecorated(true);

        jPanel1.setLayout(null);

        loadingnum.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jPanel1.add(loadingnum);
        loadingnum.setBounds(190, 210, 30, 40);

        loadingbar.setForeground(new java.awt.Color(255, 204, 51));
        loadingbar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        loadingbar.setOpaque(false);
        loadingbar.setString("");
        loadingbar.setStringPainted(true);
        jPanel1.add(loadingbar);
        loadingbar.setBounds(120, 180, 170, 20);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setorhafalan/quran-logo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(150, 10, 100, 100);

        judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        judul.setText("Sistem Informasi Hafal Quran");
        jPanel1.add(judul);
        judul.setBounds(40, 110, 320, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setorhafalan/bground.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    public static javax.swing.JProgressBar loadingbar;
    public static javax.swing.JLabel loadingnum;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
