/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setorhafalan;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    public static Login login;
    public Database database;
    public Utama utama;
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        database = new Database();
        setLocationRelativeTo(null);
    }
    public void loginAdmin(){
        
        PreparedStatement ps;
        try {
            ps = database.conn.prepareStatement("select * from admin");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                if(rs.getString(2).equals(tfusername.getText())&&rs.getString(3).equals(pfpassword.getText())){
                    JOptionPane.showMessageDialog(null, "Selamat Datang Admin");
                    utama = new Utama();
                    utama.setVisible(true);
                    utama.setLocationRelativeTo(null);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Input Salah");
                }
            }
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Belum Terkoneksi Database");
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lsubmit = new javax.swing.JLabel();
        pfpassword = new javax.swing.JPasswordField();
        lusername = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        lpassword = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        llogin = new javax.swing.JLabel();
        backgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Hafal Quran");

        jPanel1.setLayout(null);

        lsubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lsubmit.setText("Submit");
        lsubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsubmitMouseClicked(evt);
            }
        });
        jPanel1.add(lsubmit);
        lsubmit.setBounds(210, 230, 62, 30);
        jPanel1.add(pfpassword);
        pfpassword.setBounds(140, 190, 310, 19);

        lusername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lusername.setText("Username");
        jPanel1.add(lusername);
        lusername.setBounds(30, 160, 62, 17);

        tfusername.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        jPanel1.add(tfusername);
        tfusername.setBounds(140, 160, 310, 17);

        lpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lpassword.setText("Password");
        jPanel1.add(lpassword);
        lpassword.setBounds(30, 190, 56, 17);

        judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        judul.setText("Sistem Informasi Hafal Quran");
        jPanel1.add(judul);
        judul.setBounds(30, 60, 310, 22);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setorhafalan/quran-logo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(370, 10, 100, 120);

        llogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        llogin.setText("Login");
        jPanel1.add(llogin);
        llogin.setBounds(30, 130, 70, 22);

        backgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setorhafalan/bground.jpg"))); // NOI18N
        jPanel1.add(backgrond);
        backgrond.setBounds(0, 0, 490, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsubmitMouseClicked
        // TODO add your handling code here:
        loginAdmin();
    }//GEN-LAST:event_lsubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrond;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel llogin;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel lsubmit;
    private javax.swing.JLabel lusername;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
