/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setorhafalan;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xatalie
 */
public class Update extends javax.swing.JFrame {
    Database database;
    static String rbguru;
    Utama u;
    
    /**
     * Creates new form Insert
     */
    public Update() {
        initComponents();
        u = new Utama();
        setLocationRelativeTo(null);
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        tftgl.setText(dateFormat.format(date));
        tftgl.disable();
        database = new Database();
        tfnama.setText(u.nama);
        tfayatd.setText(Integer.toString(u.ad));
        tfayats.setText(Integer.toString(u.as));
        rbguru1.setText(u.g);
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lsubmit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfayatd = new javax.swing.JTextField();
        tfayats = new javax.swing.JTextField();
        tftgl = new javax.swing.JTextField();
        cbsuratd = new javax.swing.JComboBox<>();
        cbsurats = new javax.swing.JComboBox<>();
        rbguru1 = new javax.swing.JRadioButton();
        rbguru2 = new javax.swing.JRadioButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 60, 35, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Dari");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 27, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Sampai");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 45, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tanggal");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 48, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Guru");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 230, 32, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Update");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 20, 60, 20);

        lsubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lsubmit.setText("Submit");
        lsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsubmitMouseClicked(evt);
            }
        });
        jPanel1.add(lsubmit);
        lsubmit.setBounds(299, 265, 70, 20);

        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setText("Kembali");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(30, 270, 60, 23);

        tfnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfnama);
        tfnama.setBounds(130, 60, 250, 18);

        tfayatd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfayatd);
        tfayatd.setBounds(310, 100, 70, 18);

        tfayats.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfayats);
        tfayats.setBounds(310, 140, 70, 18);

        tftgl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tftgl);
        tftgl.setBounds(130, 190, 250, 18);

        cbsuratd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surat 1", "Surat 2" }));
        jPanel1.add(cbsuratd);
        cbsuratd.setBounds(130, 100, 170, 24);

        cbsurats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surat 1", "Surat 2" }));
        jPanel1.add(cbsurats);
        cbsurats.setBounds(130, 140, 170, 24);

        rbguru1.setText("Ust. Adi");
        rbguru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbguru1ActionPerformed(evt);
            }
        });
        jPanel1.add(rbguru1);
        rbguru1.setBounds(130, 230, 80, 23);

        rbguru2.setText("Ustz. Salimah");
        rbguru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbguru2ActionPerformed(evt);
            }
        });
        jPanel1.add(rbguru2);
        rbguru2.setBounds(260, 230, 122, 23);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setorhafalan/bground.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsubmitMouseClicked
        // TODO add your handling code here:
        try {
            System.err.println(u.id);
            String sql = "UPDATE hafalan SET nama='"+tfnama.getText()+"',suratd='"+cbsuratd.getModel().getSelectedItem().toString()+"',ayatd='"+Integer.parseInt(tfayatd.getText())+"',surats='"+cbsurats.getModel().getSelectedItem().toString()+"',ayats='"+Integer.parseInt(tfayats.getText())+"',tanggal='"+tftgl.getText()+"',guru='"+rbguru+"' WHERE id_h='"+u.id+"'";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            this.dispose();
            new Utama().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    }//GEN-LAST:event_lsubmitMouseClicked

    private void rbguru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbguru1ActionPerformed
        // TODO add your handling code here:
        if(rbguru1.isSelected()){
            rbguru2.setEnabled(false);
            rbguru = rbguru1.getText();
        }else if(!rbguru1.isSelected()){
            rbguru2.setEnabled(true);
        }else if(rbguru1.isSelected()&&rbguru2.isSelected()){
            JOptionPane.showMessageDialog(null, "Pilih salah satu");
        }
    }//GEN-LAST:event_rbguru1ActionPerformed

    private void rbguru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbguru2ActionPerformed
        // TODO add your handling code here:
        if(rbguru2.isSelected()){
            rbguru1.setEnabled(false);
            rbguru = rbguru2.getText();
        }else if(!rbguru2.isSelected()){
            rbguru1.setEnabled(true);
        }else if(rbguru1.isSelected()&&rbguru2.isSelected()){
            JOptionPane.showMessageDialog(null, "Pilih salah satu");
        }
    }//GEN-LAST:event_rbguru2ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Utama().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> cbsuratd;
    private javax.swing.JComboBox<String> cbsurats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lsubmit;
    private javax.swing.JRadioButton rbguru1;
    private javax.swing.JRadioButton rbguru2;
    private javax.swing.JTextField tfayatd;
    private javax.swing.JTextField tfayats;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tftgl;
    // End of variables declaration//GEN-END:variables
}
